event/urls.py
from django.urls import path

from event import views

urlpatterns = [
    path('public_events/<str:event_code>/', views.EventPublic.as_view(), name='event_public'),
    path('public_events/<str:event_code>/<uuid:problem_id>/', views.EventPublicProblem.as_view(), name='event_public_problem'),

    path('events/list/', views.EventListView.as_view(), name='events_list'),
    path('events/create/', views.EventCreate.as_view(), name='event_create'),
    path('events/update/<uuid:pk>/', views.EventUpdate.as_view(), name='event_update'),
    path('events/details/<uuid:pk>/', views.EventDetails.as_view(), name='event_details'),
    path('events/delete/<uuid:pk>/', views.EventDelete.as_view(), name='event_delete'),

]

event/models.py
import uuid

from django.conf import settings
from django.db import models
from django_quill.fields import QuillField
from model_utils.models import TimeStampedModel

from accounts.models import Company
from conf.db import EVENT_TYPE, INTERNAL_EXTERNAL, PRIVATE_PUBLIC, PHYSICAL_DIGITAL


def company_event_image_file_name(instance, filename):
    return "company_{id}/event_image/{file}".format(id=instance.company.id, file=filename)


class Event(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    description = QuillField(max_length=10000)
    code = models.CharField(max_length=20, unique=True)
    one_liner_description = models.CharField(max_length=200)
    url = models.CharField(max_length=1000, null=True, blank=True)


    date_from = models.DateField()
    date_to = models.DateField()
    problem_submission_date_from = models.DateField()
    problem_submission_date_to = models.DateField()

    event_image = models.ImageField(blank=True, null=True, upload_to=company_event_image_file_name)

    host = models.ManyToManyField(settings.AUTH_USER_MODEL, through='EventHosts', related_name='hosts_event')

    event_type = models.SmallIntegerField(choices=EVENT_TYPE, default=EVENT_TYPE.CONFERENCE)
    host_has_problem_access = models.BooleanField(default=False)


    def __str__(self):
        return self.name


class EventHosts(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

event/forms.py
import re

from allauth.account.forms import PasswordField
from django import forms
from django.forms import ModelForm
from multiselectfield import MultiSelectFormField

from conf.db import INTERNAL_EXTERNAL, PRIVATE_PUBLIC
from event.models import Event, EventResources, EventHosts, EventOnBoardedParticipants
from local_auth.forms import ProblemoFormMixin
from local_auth.models import User


class EventForm(ProblemoFormMixin, ModelForm):
    date_from = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(format='%d/%m/%Y'))
    date_to = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(format='%d/%m/%Y'))
    problem_submission_date_from = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(format='%d/%m/%Y'))
    problem_submission_date_to = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(format='%d/%m/%Y'))
    class Meta:
        model = Event
        fields = (
            'name',
            'description',
            'code',
            'one_liner_description',
            'url',

            'date_from',
            'date_to',
            'problem_submission_date_from',
            'problem_submission_date_to',

            'event_image',

            'event_type',
            'internal_or_external',
            'private_or_public',
            'physical_or_digital',

            'host_has_problem_access',
            'host_on_boards_members',
            'problem_owner_on_boards_members',
            'auto_accept_requests',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.format_field('name')
        self.format_field('description')
        self.format_field('code')
        self.format_field('one_liner_description')
        self.format_field('url')

        self.format_field('date_from')
        self.format_field('date_to')
        self.format_field('problem_submission_date_from')
        self.format_field('problem_submission_date_to')

        self.format_field('event_image')

        self.format_field('event_type')
        self.format_field('internal_or_external')
        self.format_field('private_or_public')
        self.format_field('physical_or_digital')

    def clean_code(self):
        code = self.cleaned_data.get('code')
        if len(code) < 5:
            self.add_error('code', 'Event Code Must Be At least 5 Characters')

        if not re.match(r'^[A-Za-z0-9_-]+$', code):
            self.add_error('code', 'Event Code Must Contains Alphanumeric, Underscore and Hyphen')

        return code


    def validate_date(self, data):
        start = data.get('date_from')
        end = data.get('date_to')
        if start is not None and end is not None:
            if end<start:
                self.add_error('date_from', 'Event Start Date Must Be Before End Date')
                self.add_error('date_to', 'Event End Date Must Be After Start Date')

    def validate_problem_submission_date(self, data):
        start = data.get('problem_submission_date_from')
        end = data.get('problem_submission_date_to')
        if start is not None and end is not None:
            if end < start:
                self.add_error('problem_submission_date_from', 'Problem Submission Start Date Must Be Before End Date')
                self.add_error('problem_submission_date_to', 'Problem Submission End Date Must Be After Start Date')

    def validate_private_or_public(self, clean_data):
        internal_or_external = clean_data.get('internal_or_external')
        private_or_public = clean_data.get('private_or_public')
        if internal_or_external == INTERNAL_EXTERNAL.EXTERNAL and (private_or_public is None or private_or_public ==''):
            self.add_error('private_or_public', 'This field is required.')

    def validate_host_on_boards_members(self, clean_data):
        host_on_boards_members = clean_data.get('host_on_boards_members')
        problem_owner_on_boards_members = clean_data.get('problem_owner_on_boards_members')

        if host_on_boards_members is False and problem_owner_on_boards_members is False:
            self.add_error('host_on_boards_members',
                           'The event host and/or the problem owner must having onboarding permissions. Please select at least one.')

    def adjust_data(self, clean_data):
        host_has_problem_access = clean_data.get('host_has_problem_access', False)
        internal_or_external = clean_data.get('internal_or_external')
        private_or_public = clean_data.get('private_or_public')
        if internal_or_external == INTERNAL_EXTERNAL.INTERNAL:
            self.cleaned_data.update(dict(private_or_public=None))

        if not host_has_problem_access:
            self.cleaned_data.update(dict(host_on_boards_members=False))

        if internal_or_external == INTERNAL_EXTERNAL.EXTERNAL and private_or_public == PRIVATE_PUBLIC.PRIVATE:
            self.cleaned_data.update(dict(auto_accept_requests=False))

    def clean(self):
        clean_data = super().clean()
        self.validate_date(clean_data)
        self.validate_problem_submission_date(clean_data)
        self.validate_private_or_public(clean_data)
        self.validate_host_on_boards_members(clean_data)
        self.adjust_data(clean_data)


class EventUpdateForm(EventForm):
    class Meta:
        model = Event
        fields = (
            'name',
            'description',
            'one_liner_description',
            'url',

            'date_from',
            'date_to',
            'problem_submission_date_from',
            'problem_submission_date_to',

            'event_image',

            'event_type',
            'physical_or_digital',
            'auto_accept_requests',
        )

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.format_field('name')
        self.format_field('description')
        self.format_field('one_liner_description')
        self.format_field('url')

        self.format_field('date_from')
        self.format_field('date_to')
        self.format_field('problem_submission_date_from')
        self.format_field('problem_submission_date_to')

        self.format_field('event_image')

        self.format_field('event_type')
        self.format_field('physical_or_digital')

event/views.py
import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, FormView, RedirectView

from conf.db import PROBLEM_ACTIVITY_STATUS, INTERNAL_EXTERNAL, PRIVATE_PUBLIC
from event.forms import EventDeleteForm
from event.forms import EventForm, EventResourceForm, EventInviteForm
from event.forms import EventUpdateForm
from event.models import Event, EventResources, EventHosts, EventOnBoardedParticipants, EventAwaitingParticipants
from event.permission_utils import has_permission_to_create_event, can_user_removed_from_event
from event.permission_utils import has_permission_to_update_event, has_permission_to_view_event_details
from event.utils import invite_user_to_event_as_host, invite_user_to_event_as_participant, send_mail_event_invitation, \
    get_public_events_qs, get_public_event_problems_qs
from event.utils import send_event_delete_email, invite_user_to_event_by_email, is_external_event, \
    send_event_attend_request_email, send_event_awaiting_participant_approved_email, \
    send_event_awaiting_participant_reject_email
from local_auth.models import User
from problem.models import Problem, ProblemEvents
from problem.utils import get_favicon_path, can_add_event_to_problem, is_trial_account, \
    add_event_hosts_to_problem_on_boarded_when_adding_event_to_problem
from problem.views import ProblemCreate, ProblemUpdateGoals, ProblemUpdate, ProblemCompetencyTagsCreate, \
    ProblemCompetencyTagsDelete, ProblemReview, ProblemEventsUpdate, ProblemEventsDelete, ProblemComplete


class EventListView(LoginRequiredMixin, ListView):
    template_name = 'event/event_list.html'
    context_object_name = 'events'

    def get_queryset(self):
        request_user = self.request.user
        event_filter = self.request.GET.get('filter', 'my_events')
        qs = Event.objects.all()

        today_date = timezone.now().date()

        qs = qs.exclude(Q(Q(private_or_public=PRIVATE_PUBLIC.PUBLIC),
                          ~Q(Q(host=request_user) | Q(on_boarded_participants=request_user)),
                          Q(date_to__lte=today_date)) |
                        Q(Q(internal_or_external=INTERNAL_EXTERNAL.INTERNAL),
                          Q(company=request_user.company),
                          ~Q(Q(host=request_user) | Q(on_boarded_participants=request_user)),
                          Q(date_to__lte=today_date)))

        if event_filter == 'my_events':
            qs = qs.filter(Q(host=request_user) | Q(on_boarded_participants=request_user))
        elif event_filter == 'company_events':
            qs = qs.filter(company=request_user.company)
        elif event_filter == 'all_events':
            qs = qs.filter(Q(host=request_user) |
                           Q(on_boarded_participants=request_user) |
                           Q(company=request_user.company) |
                           Q(internal_or_external=INTERNAL_EXTERNAL.EXTERNAL,
                             private_or_public=PRIVATE_PUBLIC.PUBLIC,
                             date_to__gte=today_date)
                           )

        qs = qs.distinct()
        qs = qs.order_by('date_from')
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['can_create_event'] = has_permission_to_create_event(self.request.user)
        context['events_filter'] = self.request.GET.get('filter', 'my_events')
        context['is_trial_account'] = is_trial_account(self.request.user)
        return context


class EventCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = EventForm
    template_name = 'event/event_form.html'


    def get_initial(self):
        initial = super().get_initial()
        initial['private_or_public'] = PRIVATE_PUBLIC.PRIVATE
        return initial

    def has_permission(self):
        return has_permission_to_create_event(self.request.user)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.company = self.request.user.company
        obj.host.set([self.request.user])
        obj.save()

        return HttpResponseRedirect(reverse_lazy('events_list'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = "Create Event"
        context['button_label'] = "Create"
        return context


class EventUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    form_class = EventUpdateForm
    template_name = 'event/event_update_form.html'
    success_url = reverse_lazy('events_list')

    def has_permission(self):
        event_id = self.kwargs.get('pk')
        return has_permission_to_update_event(self.request.user.id, event_id)

    def get_queryset(self):
        return Event.objects.filter(id__in=EventHosts.objects.filter(user=self.request.user).values_list('event_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = "Update Event"
        context['button_label'] = "Update"
        context['update_view'] = True
        context['event_id'] = self.kwargs.get('pk')
        return context


class EventDetails(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    template_name = 'event/event_detail.html'
    context_object_name = 'event'

    def has_permission(self):
        event_id = self.kwargs.get('pk')
        return has_permission_to_view_event_details(self.request.user.id, event_id)

    def get_queryset(self):
        return Event.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = context['event']
        request_user_in_event_host = EventHosts.objects.filter(event=event, user=self.request.user)
        event_host_count = EventHosts.objects.filter(event=event).count()
        resources_qs = EventResources.objects.filter(event=event)


        context['event_duration_between_today'] = event.date_from <= timezone.now().date() <= event.date_to
        context['request_user_in_event_host'] = request_user_in_event_host
        context['event_host_count'] = event_host_count
        context['resources_for_event_host'] = resources_qs.filter(event=event, visible_only_to_event_host=True)
        context['resources_for_everyone'] = resources_qs.filter(event=event, visible_only_to_event_host=False)
        context['hosts'] = self.get_event_hosts(event)

        return context

    @staticmethod
    def get_event_hosts(event):
        qs =  EventHosts.objects.filter(event=event).select_related('user', 'user__company')
        return qs.order_by('-user__is_active', 'user__first_name', 'user__last_name')

    @staticmethod
    def get_event_participants(event):
        qs =  EventOnBoardedParticipants.objects.filter(event=event).select_related('user', 'user__company')
        return qs.order_by('-user__is_active', 'user__first_name', 'user__last_name')


class EventDelete(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    success_url = reverse_lazy('events_list')
    form_class = EventDeleteForm
    template_name = 'event/event_delete.html'

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        request_user = self.request.user

        if not request_user.check_password(cleaned_data.get('password')):
            form.add_error('password', 'Password is not correct')
            return self.form_invalid(form)

        event = Event.objects.get(id=self.kwargs.get('pk'))
        send_event_delete_email(event, self.request.user)
        event.delete()
        messages.info(self.request, 'event deleted successfully')

        return super().form_valid(form)

    def has_permission(self):
        event_id = self.kwargs.get('pk')
        return has_permission_to_update_event(self.request.user.id, event_id)

    def get_context_data(self, **kwargs):
        context = super(EventDelete, self).get_context_data(**kwargs)
        context['event'] = Event.objects.get(id=self.kwargs.get('pk'))
        return context

templates/event/event_delete.html
{% extends "problem/base.html" %}
{% load static %}

{% block background_top %}
    <style>
        #kt_body {
            background-image: url({% static 'img/bg-04.png' %});
        }

        .header {
            background-color: #6985fb;
        }
    </style>
{% endblock %}

{% block top_menu %}
    {% include 'problem/nav_bar.html' with current_menu="events" %}
{% endblock %}

{% block container %}
    <!--begin::Card-->
    <div class="card card-custom card-shadowless rounded-top-0">
        <!--begin::Body-->
        <div class="card-body p-0">
            <div class="row justify-content-center py-8 px-8 py-lg-15 px-lg-10">
                <div class="col-xl-12 col-xxl-10">
                    <div class="d-flex justify-content-between border-bottom mb-5 pb-10">
                        <div>
                            <a href="{% url 'event_details' pk=event.id %}" class="btn btn-secondary font-weight-bolder text-capital px-9 py-4" data-wizard-type="action-next"><i class="ki ki-bold-long-arrow-back"></i> Back to event workspace</a>
                        </div>
                    </div>
                    <form class="form" id="kt_form" method="POST" novalidate="novalidate">
                     {% csrf_token %}
                        <div class="row">
                            <div class="col-xl-12">
                                <p>Are you sure you want to delete the event? This is an irreversible action. If you still want to delete the event, please confirm with your password.</p>
                                <div class="form-group row">
                                    <label class="col-xl-1 col-lg-2 col-md-2 col-sm-12 col-form-label">Password</label>
                                    <div class="col-lg-4 col-xl-3 col-md-6 col-sm-12">
                                        {{ form.password }}
                                        {% include 'snippets/field_error.html' with errors=form.password.errors %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xl-12">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <button type="submit"
                                                class="btn btn-primary font-weight-bolder px-9 py-4 pull-right"
                                                data-wizard-type="action-next"><i class="fa la-check-circle"></i>&nbsp;Confirm
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <!--end::Body-->
    </div>
    <!--end::Card-->
{% endblock %}

templates/event/event_update_form.html
{% extends "event/event_form.html" %}

{% load static %}

{% block form_fields %}
<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label text-left">Event Image</label>
    <div class="col-md-9 col-lg-9 col-xl-9">
        <div class="image-input image-input-outline" id="kt_user_add_avatar">
            {% if form.instance.event_image %}

                <div class="image-input-wrapper"
                     style="background-image: url( {{ form.instance.event_image.url }})"></div>
            {% elif user.company.logo %}
                <div class="image-input-wrapper"
                     style="background-image: url( {{ user.company.logo.url }})"></div>

            {% else %}
                <div class="image-input-wrapper"
                     style="background-image: url({% static 'img/default_event_image.png' %})"></div>
            {% endif %}

            <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                   data-action="change" data-toggle="tooltip" title=""
                   data-original-title="Change event image">
                <i class="fa fa-pen icon-sm text-muted"></i>

                <input type="file" name="event_image" id="id_event_image"
                       accept=".png, .jpg, .jpeg">
                <input type="checkbox" name="event_image-clear" id="event_image-clear_id">
                {% include 'snippets/field_error.html' with errors=form.event_image.errors %}

            </label>
            <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                  data-action="cancel" data-toggle="tooltip" title="Cancel event image">
            <i class="ki ki-bold-close icon-xs text-muted"></i>
        </span>
        </div>
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event Name</label>
    <div class="col-md-9 col-lg-9 col-xl-9">
        {{ form.name }}
        {% include 'snippets/field_error.html' with errors=form.name.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event One Liner Description</label>
    <div class="col-md-9 col-lg-9 col-xl-9">
        {{ form.one_liner_description }}
        {% include 'snippets/field_error.html' with errors=form.one_liner_description.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event External website</label>
    <div class="col-md-9 col-lg-9 col-xl-9">
        {{ form.url }}
        {% include 'snippets/field_error.html' with errors=form.url.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event Description</label>
    <div class="col-md-9 col-lg-9 col-xl-9">
        {{ form.description }}
        {% include 'snippets/field_error.html' with errors=form.description.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event Date From</label>
    <div class="col-lg-3 col-xl-3 col-md-4 col-sm-6 col-xs-12">
        <div class="input-group input-group-solid">
            {{ form.date_from }}
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="la la-calendar"></i>
                </span>
            </div>
        </div>
        {% include 'snippets/field_error.html' with errors=form.date_from.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event Date To</label>
    <div class="col-lg-3 col-xl-3 col-md-4 col-sm-6 col-xs-12">
        <div class="input-group input-group-solid">
            {{ form.date_to }}
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="la la-calendar"></i>
                </span>
            </div>
        </div>
        {% include 'snippets/field_error.html' with errors=form.date_to.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Problem Submission Date From</label>
    <div class="col-lg-3 col-xl-3 col-md-4 col-sm-6 col-xs-12">
        <div class="input-group input-group-solid">
            {{ form.problem_submission_date_from }}
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="la la-calendar"></i>
                </span>
            </div>
        </div>
        {% include 'snippets/field_error.html' with errors=form.problem_submission_date_from.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Problem Submission Date To</label>
    <div class="col-lg-3 col-xl-3 col-md-4 col-sm-6 col-xs-12">
        <div class="input-group input-group-solid">
            {{ form.problem_submission_date_to }}
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="la la-calendar"></i>
                </span>
            </div>
        </div>
        {% include 'snippets/field_error.html' with errors=form.problem_submission_date_to.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event Type</label>
    <div class="col-lg-3 col-xl-3 col-md-4 col-sm-6 col-xs-12">
        {{ form.event_type }}
        {% include 'snippets/field_error.html' with errors=form.event_type.errors %}
    </div>
</div>

<div class="form-group row">
    <label class="col-xl-3 col-lg-3 col-md-3 col-form-label">Event Physical Or Digital</label>
    <div class="col-lg-3 col-xl-3 col-md-4 col-sm-6 col-xs-12">
        {{ form.physical_or_digital }}
        {% include 'snippets/field_error.html' with errors=form.physical_or_digital.errors %}
    </div>
</div>

{% if form.instance.is_event_internal_or_external_public %}
    <div class="form-group row pb-0 mb-0" id="id_div_auto_accept_requests">
        <div class="col-xs-0 col-sm-3 col-md-3 col-lg-3 col-xl-3"></div>
        <div class="col-lg-6 col-xl-6 col-md-9 col-sm-12 col-xs-12">
            {{ form.auto_accept_requests }}<label class="col-xl-9 col-lg-9 label-inline">Auto accept event attend request</label>
            {% include 'snippets/field_error.html' with errors=form.auto_accept_requests.errors %}
        </div>
    </div>
{% endif %}
{% endblock %}